### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by KillovSky** [ToinNetuh/Tatakaer#1]
Olá @ToinNetuh, me parece que alguns comandos de seu devido projeto foram pegos de meu projeto Iris, obviamente, a prova é a data de publicação dos commits em ambos repositórios, você sabe que ao pegar "emprestado" o código de um desenvolvedor é necessário lhe dar os créditos do código adquirido certo?
Não analisei seus outros códigos, mas se houver algo mais, peço que por gentileza forneça os créditos (não só a mim, mas a todos que você utiliza de base), de toda forma, foi um honra falar com você.

Aguardarei por respostas, agradecido, KillovSky.

![image](https://user-images.githubusercontent.com/55511420/110745010-61b55880-8219-11eb-8b1f-064ddfd8609e.png)

**Comment by ToinNetuh** [comment]
a git era privada nem divulguei nem nd do tipo peço desculpas vo privar ela

Em ter, 15 de jun de 2021 12:46, KillovSky ***@***.***>
escreveu:
